Задание 5. Реализация степенного метода и метода скалярных произведений

In [12]:
! pip install numpy
! pip install scipy

In [13]:
import numpy as np
from scipy.linalg import hilbert

Реализация степенного метода

In [14]:
def pow_method(a, eps = 1e-5, max_iter = 10000):
    x = np.array([ 1. ] * len(a))
    new_x = np.dot(a, x)
    x_prev = np.copy(x)
    x = new_x
    eigenval = np.sqrt(np.dot(x, x) / np.dot(x_prev, x_prev))
    iterations = 1
    while True:
        new_x = np.dot(a, x)
        x_prev = np.copy(x)
        x = new_x
        if iterations % 3 == 0:
            x /= np.linalg.norm(x)
        eigenval_prev = eigenval
        eigenval = np.sqrt(np.dot(x, x) / np.dot(x_prev, x_prev))
        iterations += 1
        if abs(eigenval - eigenval_prev) < eps:
            break
        assert iterations < max_iter, "Превышено количество итераций!"
    return x, eigenval, iterations

Реализация метода скалярных произведений

In [15]:
def scalar_product_method(a, eps = 1e-5, max_iter = 10000):
    x = np.array([ 1. ] * len(a))
    y = np.array([ 1. ] * len(a))
    new_x = np.dot(a, x)
    x_prev = np.copy(x)
    x = new_x
    y = np.dot(a.T, y)
    eigenval = np.dot(x, y) / np.dot(x_prev, y)
    iterations = 1
    while True:
        new_x = np.dot(a, x)
        x_prev = np.copy(x)
        x = new_x
        if iterations % 3 == 0:
            x /= np.linalg.norm(x)
        y = np.dot(a.T, y)
        eigenval_prev = eigenval
        eigenval = np.dot(x, y) / np.dot(x_prev, y)
        iterations += 1
        if abs(eigenval - eigenval_prev) < eps:
            break
        assert iterations < max_iter, "Превышено количество итераций!"
    return x, eigenval, iterations

Тестирование степенного метода на случайной матрице

In [16]:
def test_pow_method(a, eps):
    res = pow_method(a, eps)
    print("\tТочность:", eps)
    print("\tСобственный вектор:",res[0])
    print("\tСобственное число:", res[1])
    print("\tКоличество итераций:", res[2])
    print("\ta * eigenvector =", np.dot(a, res[0]), "\n\teigenvector * eigenvalue =", res[0] * res[1])
    print("\tРешение корректно:", np.allclose(np.dot(a, res[0]), res[0] * res[1]))

N = 3
print("Тестирование на рандомной матрице порядка", N)
a = np.random.rand(N, N)
print(a)
print("1)")
test_pow_method(a, 1e-5)
print("2)")
test_pow_method(a, 1e-9)

Тестирование на рандомной матрице порядка 3
[[0.01178419 0.0791476  0.98246189]
 [0.98691097 0.45024807 0.3999658 ]
 [0.4614561  0.11768709 0.73744724]]
1)
	Точность: 1e-05
	Собственный вектор: [0.73526117 1.25822079 0.86391102]
	Собственное число: 1.3015907255612904
	Количество итераций: 9
	a * eigenvector = [0.95700928 1.63768365 1.12445589] 
	eigenvector * eigenvalue = [0.95700912 1.63768851 1.12445858]
	Решение корректно: True
2)
	Точность: 1e-09
	Собственный вектор: [0.73526418 1.25822297 0.86391285]
	Собственное число: 1.3015883335383476
	Количество итераций: 18
	a * eigenvector = [0.95701128 1.63768834 1.12445889] 
	eigenvector * eigenvalue = [0.95701128 1.63768834 1.12445889]
	Решение корректно: True


Тестирование степенного метода на матрице Гильберта

In [17]:
N = 3
print("Тестирование на матрице Гильберта порядка", N)
a = hilbert(N)
#print(a)
print("1)")
test_pow_method(a, 1e-5)
print("2)")
test_pow_method(a, 1e-9)

Тестирование на матрице Гильберта порядка 3
1)
	Точность: 1e-05
	Собственный вектор: [1.64032946 0.91207686 0.64121811]
	Собственное число: 1.4083189271210397
	Количество итераций: 6
	a * eigenvector = [2.31010726 1.28449488 0.90303933] 
	eigenvector * eigenvalue = [2.31010703 1.28449511 0.9030396 ]
	Решение корректно: True
2)
	Точность: 1e-09
	Собственный вектор: [1.64032946 0.91207686 0.64121811]
	Собственное число: 1.4083189271210397
	Количество итераций: 6
	a * eigenvector = [2.31010726 1.28449488 0.90303933] 
	eigenvector * eigenvalue = [2.31010703 1.28449511 0.9030396 ]
	Решение корректно: True


Тестирование метода скалярных произведений на матрице из методички А. Н. Пакулиной

In [18]:
def test_scalar_product_method(a, eps):
    res = scalar_product_method(a, eps)
    print("\tТочность:", eps)
    print("\tСобственный вектор:",res[0])
    print("\tСобственное число:", res[1])
    print("\tКоличество итераций:", res[2])
    print("\ta * eigenvector =", np.dot(a, res[0]), "\n\teigenvector * eigenvalue =", res[0] * res[1])
    print("\tРешение корректно:", np.allclose(np.dot(a, res[0]), res[0] * res[1]))

N = 3
print("Тестирование на матрице из методички А. Н. Пакулиной порядка", N)
a = np.array([
    [-0.81417, -0.01937, 0.41372],
    [-0.01937, 0.54414, 0.00590],
    [0.41372, 0.00590, -0.81445]
])
print(a)
print("1)")
test_scalar_product_method(a, 1e-5)
print("2)")
test_scalar_product_method(a, 1e-9)

Тестирование на матрице из методички А. Н. Пакулиной порядка 3
[[-0.81417 -0.01937  0.41372]
 [-0.01937  0.54414  0.0059 ]
 [ 0.41372  0.0059  -0.81445]]
1)
	Точность: 1e-05
	Собственный вектор: [-1.06657473 -0.01446289  1.06666214]
	Собственное число: -1.228211125004802
	Количество итераций: 15
	a * eigenvector = [ 1.30995276  0.01908302 -1.31009161] 
	eigenvector * eigenvalue = [ 1.30997895  0.01776349 -1.31008631]
	Решение корректно: False
2)
	Точность: 1e-09
	Собственный вектор: [-1.06655991 -0.01520164  1.06667316]
	Собственное число: -1.2282101510216676
	Количество итераций: 21
	a * eigenvector = [ 1.30995956  0.01868082 -1.31009882] 
	eigenvector * eigenvalue = [ 1.30995971  0.01867081 -1.31009881]
	Решение корректно: False


Тестирование метода скалярных произведений на матрице Гильберта

In [19]:
N = 3
print("Тестирование на матрице Гильберта порядка", N)
a = hilbert(N)
#print(a)
print("1)")
test_scalar_product_method(a, 1e-5)
print("2)")
test_scalar_product_method(a, 1e-9)

Тестирование на матрице Гильберта порядка 3
1)
	Точность: 1e-05
	Собственный вектор: [1.64032946 0.91207686 0.64121811]
	Собственное число: 1.4083189271232361
	Количество итераций: 6
	a * eigenvector = [2.31010726 1.28449488 0.90303933] 
	eigenvector * eigenvalue = [2.31010703 1.28449511 0.9030396 ]
	Решение корректно: True
2)
	Точность: 1e-09
	Собственный вектор: [1.64032946 0.91207686 0.64121811]
	Собственное число: 1.4083189271232361
	Количество итераций: 6
	a * eigenvector = [2.31010726 1.28449488 0.90303933] 
	eigenvector * eigenvalue = [2.31010703 1.28449511 0.9030396 ]
	Решение корректно: True


Сравнение количества итераций

In [20]:
N = 10
a = np.random.rand(N, N)
print("Точность:", 1e-5)
pow_iters = pow_method(a, 1e-5)[2]
print("\tСтепенной метод:", pow_iters)
sp_iters = scalar_product_method(a, 1e-5)[2]
print("\tМетод скалярных произведений:", sp_iters)
print("Точность:", 1e-10)
pow_iters = pow_method(a, 1e-10)[2]
print("\tСтепенной метод:", pow_iters)
sp_iters = scalar_product_method(a, 1e-10)[2]
print("\tМетод скалярных произведений:", sp_iters)

Точность: 1e-05
	Степенной метод: 9
	Метод скалярных произведений: 6
Точность: 1e-10
	Степенной метод: 15
	Метод скалярных произведений: 9
