Задание 3. Решение СЛАУ методом QR-разложения

In [1]:
!pip3 install numpy
!pip3 install scipy

In [2]:
import numpy as np
from scipy.linalg import hilbert

Реализация метода решения СЛАУ

In [3]:
def decomposition(a):
    q = np.eye(len(a))
    r = a
    rows, cols = np.tril_indices(len(a), -1, len(a))
    for i, j in zip(rows, cols):
            norm = np.sqrt(r[j][j] * r[j][j] + r[i][j] * r[i][j])
            c = r[j][j] / norm
            s = -r[i][j] / norm
            t = np.eye(len(a))
            t[i][i] = t[j][j] = c
            t[i][j] = s
            t[j][i] = -s
            r = np.matmul(t, r)
            q = np.matmul(q, t.T)
    return q, r

def QR(a, b):
    q, r = decomposition(a)
    return np.linalg.solve(r, np.linalg.solve(q, b))

Функции для вычисления чисел обусловленности

In [4]:
def cond_s(a):
    return np.linalg.norm(a) * np.linalg.norm(np.linalg.inv(a))

def cond_v(a):
    det_a = abs(np.linalg.det(a))
    return np.prod([np.sqrt(sum(x * x for x in row)) for row in a]) / det_a

def cond_a(a):
    temp = []
    for i in range(len(a)):
        tmp_val = np.sqrt(sum(x * x for x in a[i]))
        column = np.array(np.linalg.inv(a)[:,i])
        tmp_val *= np.sqrt(sum(x * x for x in column))
        temp.append(tmp_val)
    return max(temp)

Тест 1

In [5]:
N = 6
a = np.random.random((N, N))
print("Спектральный критерий обусловленности 'a':", cond_s(a))
print("Объемный критерий обусловленности 'a':", cond_v(a))
print("Угловой критерий обусловленности 'a':", cond_a(a))
b = np.random.rand(N)
print("Решение с помощью QR-разложения:\n\t", QR(a, b))
print("Библиотечная реализация:\n\t", np.linalg.solve(a, b))

Спектральный критерий обусловленности 'a': 89.47387173257933
Объемный критерий обусловленности 'a': 488.32982627093696
Угловой критерий обусловленности 'a': 14.39243624000386
Решение с помощью QR-разложения:
	 [-2.63643791 -5.69488419  7.05773917  4.63949189  3.57373887 -3.35692758]
Библиотечная реализация:
	 [-2.63643791 -5.69488419  7.05773917  4.63949189  3.57373887 -3.35692758]


Тест 2

In [6]:
a = hilbert(N)
print("Спектральный критерий обусловленности 'a':", cond_s(a))
print("Объемный критерий обусловленности 'a':", cond_v(a))
print("Угловой критерий обусловленности 'a':", cond_a(a))
b = np.random.rand(N)
print("Решение с помощью QR-разложения:\n\t", QR(a, b))
print("Библиотечная реализация:\n\t", np.linalg.solve(a, b))

Спектральный критерий обусловленности 'a': 15118987.12835571
Объемный критерий обусловленности 'a': 3955105185818520.5
Угловой критерий обусловленности 'a': 2441571.413401966
Решение с помощью QR-разложения:
	 [   -5390.38025643   155105.04872175 -1052718.18194012  2742523.02540278
 -3029858.03391827  1194514.35691361]
Библиотечная реализация:
	 [   -5390.38025694   155105.04873637 -1052718.18203789  2742523.02565471
 -3029858.03419424  1194514.35702167]


Тест 3

In [11]:
N = 16
a = hilbert(N)
print("Спектральный критерий обусловленности 'a':", cond_s(a))
print("Объемный критерий обусловленности 'a':", cond_v(a))
print("Угловой критерий обусловленности 'a':", cond_a(a))
b = np.random.rand(N)
print("Решение с помощью QR-разложения:\n\t", QR(a, b))
print("Библиотечная реализация:\n\t", np.linalg.solve(a, b))
solution = QR(a, b)
print(np.allclose(np.dot(a, solution), b))
print(np.dot(a, solution))
print(b)

Спектральный критерий обусловленности 'a': 3.246772869786853e+18
Объемный критерий обусловленности 'a': 3.8911155551151083e+127
Угловой критерий обусловленности 'a': 1.9075159954850627e+17
Решение с помощью QR-разложения:
	 [-6.55923159e+08  9.34690789e+10 -3.20767585e+12  4.52740314e+13
 -3.09188749e+14  9.42700018e+14  3.53057509e+14 -1.29054901e+16
  4.66157841e+16 -8.36226453e+16  7.28592767e+16  1.68263402e+15
 -7.26184254e+16  7.50600868e+16 -3.43289350e+16  6.22898673e+15]
Библиотечная реализация:
	 [-9.49374139e+09  1.50362264e+12 -5.84410739e+13  9.71997376e+14
 -8.55121884e+15  4.38344973e+16 -1.34874182e+17  2.36582850e+17
 -1.65898360e+17 -1.61736034e+17  3.87458904e+17 -8.95896273e+16
 -4.42067169e+17  5.68307173e+17 -2.91647646e+17  5.72657699e+16]
False
[-8.    -1.     1.     1.5    2.     0.     0.5    0.5    1.25   1.25
  1.25   1.75  -0.5   -0.25   0.5    0.375]
[0.12984729 0.5341297  0.23432155 0.88380628 0.56820156 0.434075
 0.45121205 0.33221746 0.34084129 0.951501

Тест 4

In [8]:
a = np.array([
    [9.016024, 1.082197, -2.783575],
    [1.082197, 4.543595, 0.647647],
    [-2.783575, 0.647647, 5.432541]
])
print("Спектральный критерий обусловленности 'a':", cond_s(a))
print("Объемный критерий обусловленности 'a':", cond_v(a))
print("Угловой критерий обусловленности 'a':", cond_a(a))
b = np.array([0., 0., 1.])
print("Решение с помощью QR-разложения:\n\t", QR(a, b))
print("Библиотечная реализация:\n\t", np.linalg.solve(a, b))

Спектральный критерий обусловленности 'a': 4.7447362217052
Объемный критерий обусловленности 'a': 1.5864033791739987
Угловой критерий обусловленности 'a': 1.5751033261417244
Решение с помощью QR-разложения:
	 [ 0.07702708 -0.05107843  0.22963314]
Библиотечная реализация:
	 [ 0.07702708 -0.05107843  0.22963314]
